version: '3.3'
services:
  php:
    build: .docker/php
    ports:
      - 3000:3000
    volumes:
      - .:/jigsaw
      - ~/.composer:/root/.composer
    environment:
      XDEBUG_CONFIG: "client_host=172.17.0.1 client_port=9003 start_with_request=yes"
